#i!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 TAG_NAME"
	exit 1
fi

TAG="$1"
HASH=`git rev-parse HEAD`

echo "package com.jeffdisher.cacophony.utils;"
echo
echo
echo "/**"
echo " * Generated by generate_version_file.sh"
echo " * The TAG defaults to EXPERIMENTAL unless set when building via \"ant -Dversion=TAG\""
echo " */"
echo "public class Version"
echo "{"
echo "\tpublic static final String TAG = \"$TAG\";"
echo "\tpublic static final String HASH = \"$HASH\";"
echo "}"
